name: workflows, jobs, and steps
on:
    workflow_dispatch:
jobs:
    job-1:
        runs-on: ubuntu-24.04
        steps:
            - run: echo "A job consists of"
            - run: echo "one or more steps"
            - run: echo "which run sequentially"
            - run: echo "within the same compute environment"
    job-2:
        runs-on: ubuntu-24.04
        steps:
            - run: echo "Job2"
    job-3:
        runs-on: ubuntu-24.04
        needs:
            - job-1
            - job-2
        steps:
            - run: echo "hi job3"
    job-4:
        runs-on: ubuntu-24.04
        needs:
            - job-2
            - job-3
        steps:
            - run: echo "all jobs are completed"