name: Step Types
on:
    workflow_dispatch:
jobs:
    say-hello-inline-bash:
        runs-on: ubuntu-24.04
        steps:
            - run: echo "hi there"
    say-hello-inline-python:
        runs-on: ubuntu-24.04
        steps:
            - run: print("hello")
              shell: python
    say-hello-action:
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/hello-world-javascript-action@081a6d193d1dcb38460df1e6927486d748730f9d
              with:
                who-to-greet: "from an action in the GitHub Action marketplace! 👋"